version: '3.7'
services:
  magma-rooms:
    build: ./docker/dev
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/app
    working_dir: /
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production

  redis:
    image: redis:5-alpine

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: magma-room
    volumes:
      - ./pgdata:/var/libpostgresql/data
    ports:
      - '5432:5432'

