version: '3.7'
services:
  magma-rooms:
    build: ./docker/dev
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=prod

  redis:
    image: redis:5-alpine

  postgres:
    image: postgres:11.2-alpine
    environment:
        POSTGRES_PASSWORD: postgres,
        POSTGRES_USER: postgres,
        POSTGRES_DB: magma-rooms
    volumes:
      - ./pgdata:/var/libpostgresql/data
    ports:
      - '5432:5432'
volumes:
  dbvolume:

